version: '3.8'

services:
  backend:
    build:
      context: ./solenix
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./satellite-events-client
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
